deployment:
  replicas: 1
  image: skyere/greencity-front:latest
  requests:
    cpu: 2m
    memory: 3Mi
  limits:
    cpu: 300m
    memory: 150Mi

service:
# ClusterIP, NodePort or LoadBalancer
  type: ClusterIP

# You need Nginx ingress controller and cert manager already installed
# https://kubernetes.github.io/ingress-nginx/deploy/
# https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions
ingress:
  hostname: www.greencity.cx.ua
  
