apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-greencity-client-service
spec:
  type: {{.Values.service.type}}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-greencity-client